### ISSUE TITLE
Some questions about operation

### ISSUE THREAD

**Issue by Jorman** [ondrovic/docker-watchdog#1]
Hi, I come from autoheal, and it seems like a good idea this project, currently the solution I adopt is not working 100%, and I don't know exactly why, it happens mainly during startup.

I would like to ask you some things about it though, it seems to me that there are some things to fix, but maybe I am wrong and just confused how to configure it.

First thing, in the Dockerfile
https://github.com/ondrovic/docker-watchdog/blob/master/Dockerfile#L7C1-L7C44
Actually now the file is in the watchdog folder, so it does not do the build

Then, checking the logs, I noticed this
```
Port '' on container 'vpn' is closed. Restarting VPN and dependencies.
Failed to restart 'vpn'
```
I then investigated and notice that in the script you call up
```
# Load the .env file from the current directory (/usr/local/bin)
set -a  # Automatically export all variables
source "/usr/local/bin/.env"
set +a  # Stop exporting all variables automatically

VPN_CONTAINER="vpn"                 # Name of the VPN container
DEPENDENT_CONTAINERS=("torrent")    # Add dependent containers here
PORT_VAR="${TORRENT}"     
```
There's no information on this, though, so I have to ask, how does this work?
Because from the instructions it looks like you just sufficed to insert the watchdog as a service and it automatically recognizes the dependent services, and that would be convenient, so that you can insert a watchdog in all dockers consisting of multiple services, but you seem to be changing things.

How can I configure this?

**Comment by ondrovic** [comment]
@Jorman thanks for reaching out, I have been running it since I before I pushed it up to to github, and it has been working really great for me. So I forked it from my actual media stack project and released it as a standalone. Let me check the code to make sure it's the same (can't remember if I made changes or not)>

As far as the logs no passing the port (which is feed via your `.env` file), would you mind sharing your docker compose / .env just so I can take a look? If not that's fine


<details>
<summary>Below is how I have it setup in my media stack project that is actually running it</summary>

```yaml
name: media

services:
  # ensures the containers heal themselves
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - TZ=${TIMEZONE}
    network_mode: none
    restart: always

  # reverse proxy
  traefik:
    image: traefik:latest
    container_name: dashboard
    ports:
      - "${HTTP}:${HTTP}" # HTTP
      - "${HTTPS}:${HTTPS}" # HTTPS
      - "${PROXY_DASHBOARD}:${PROXY_DASHBOARD}" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./traefik/users.txt:/etc/traefik/users.txt
      - ./certs:/certs:ro # Mount local certificates
      # - /Volumes/Containers/Services/Media/traefik/users.txt:/etc/traefik/users.txt
      # - /Volumes/Containers/Services/Media/certs:/certs:ro # Mount local certificates
    command:
      - "--api.insecure=true" # Enable dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--ping"
    labels:
      # Dashboard router
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # Basic auth middleware
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users.txt"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f traefik || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # dns server - I use this at a router level
  dns:
    image: ubuntu/bind9:9.20-24.10_edge
    container_name: dns
    ports:
      - "${DNS:-53}:${DNS:-53}" # DNS
      - "${DNS:-53}:${DNS:-53}/udp"
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - bind_config:/etc/bind:rw
      - bind_data:/var/cache/bind:rw
      - bind_records:/var/lib/bind:rw
      - ${CONFIG_ROOT}/dns/config/rndc.key:/etc/bind/rndc.key:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dns.rule=Host(`dns.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.dns.tls=true"
      - "traefik.http.services.dns.loadbalancer.server.port=${DNS_WEB_UI}"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f bind || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # vpn - torrent only
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${TORRENT}:${TORRENT}"
      - "${TORRENT}:${TORRENT}/udp"
      - "${TORRENT_WEB}:${TORRENT_WEB}"
    volumes:
      - config_vpn:/gluetun:rw
      - ./wg0.conf:/gluetun/wireguard/wg0.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - FIREWALL_VPN_INPUT_PORTS=${TORRENT}
    restart: always

  # sonarr - pvr for tv shows
  tv:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK}
    volumes:
      - config_sonarr:/config:rw
      - download:/mnt/downloads:rw
      - media_tv:/mnt/media:rw
    ports:
      - ${SONARR}:${SONARR}
    labels:
      - "depends_on=torrent,prowlarr"
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=${SONARR}"
    depends_on:
      torrent:
        condition: service_healthy
        restart: true
      prowlarr:
        condition: service_healthy
        restart: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f /app/sonarr/bin/Sonarr || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # radarr - pvr for movies
  movies:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK}
    volumes:
      - config_radarr:/config:rw
      - download:/mnt/downloads:rw
      - media_movies:/mnt/media:rw
    ports:
      - ${RADARR}:${RADARR}
    labels:
      - "depends_on=torrent,prowlarr"
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=${RADARR}"
    depends_on:
      torrent:
        condition: service_healthy
        restart: true
      prowlarr:
        condition: service_healthy
        restart: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f /app/radarr/bin/Radarr || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # byparr - new capture - seems to be working
  captcha:
    image: ghcr.io/thephaseless/byparr:main
    container_name: captcha
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - captcha_screenshots:/app/screenshots
    ports:
      - ${CAPTCHA}:${CAPTCHA}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.captcha.rule=Host(`captcha.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.captcha.tls=true"
      - "traefik.http.services.captcha.loadbalancer.server.port=${CAPTCHA}"
    restart: always

  # prowlarr - prowlarr for sonarr, radarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK}
    volumes:
      - config_prowlarr:/config:rw
    ports:
      - ${PROWLARR}:${PROWLARR}
    labels:
      - "depends_on=captcha"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=${PROWLARR}"
    depends_on:
      captcha:
        condition: service_healthy
        restart: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f /app/prowlarr/bin/Prowlarr || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # qbittorrent - hadnles downloading of content
  torrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    environment:
      - WEBUI_PORT=${TORRENT_WEB}
      - TORRENTING_PORT=${TORRENT}
      - PORT=${TORRENT}
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK}
    volumes:
      - config_qbittorrent:/config:rw
      - download:/mnt/downloads:rw
    labels:
      - "depends_on=vpn"
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=${TORRENT_WEB}"
    depends_on:
      vpn:
        condition: service_healthy
        restart: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep qbittorrent || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # kometa - handles media for movies
  manager:
    image: linuxserver/kometa:latest
    container_name: manager
    environment:
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIME=03:00
      - KOMETA_RUN=False
      - KOMETA_NO_MISSING=False
      - TZ=${TIMEZONE}
    volumes:
      - config_kometa:/config:rw
      - kometa_assets:/app/kometa/config/assets:rw
      - media:/mnt/media:rw
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep python3 || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # watchtower - handles updating containers automatically
  updater:
    image: containrrr/watchtower:latest
    container_name: updater
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - TZ=${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  # portainer - web ui container manager
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --ssl
      - --no-analytics
    labels:
      - "traefik.enable=true"
      - "trafeik.accessLog=true"
      - "traefik.metrics.addInternals=true"
      - "trafik.tracing=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.routers.portainer-http.middlewares=https-redirect"
      # HTTPS configuration
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" # Portainer's internal HTTP port
      # Middleware for HTTPS redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    restart: always
    healthcheck:
      test: [ "CMD", "/docker", "container", "top", "portainer" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

  # homarr - dashboard for apps
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - config_homarr:/app/data/configs
      - icons_homarr:/app/public/icons
      - data_homarr:/data
    ports:
      - ${HOMARR}:${HOMARR}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.services.homarr.loadbalancer.server.port=${HOMARR}"
    restart: always

  # uptime - monitors uptime of each container, emails if goes down
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    depends_on:
      vpn:
        condition: service_healthy
        restart: true
      torrent:
        condition: service_healthy
        restart: true
      movies:
        condition: service_healthy
        restart: true
      tv:
        condition: service_healthy
        restart: true
      prowlarr:
        condition: service_healthy
        restart: true
      homarr:
        condition: service_healthy
        restart: true
      portainer:
        condition: service_healthy
        restart: true
      manager:
        condition: service_healthy
        restart: true
      captcha:
        condition: service_healthy
        restart: true
      dns:
        condition: service_healthy
        restart: true
    volumes:
      - uptime_kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.uptime-http.rule=Host(`uptime.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.uptime-http.entrypoints=web"
      - "traefik.http.routers.uptime-http.middlewares=https-redirect"
      # HTTPS configuration
      - "traefik.http.routers.uptime.rule=Host(`uptime.${DNS_DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.tls=true"
      - "traefik.http.services.uptime.loadbalancer.server.port=${UPTIME_CONTAINER}" # Uptime Kuma's internal port
      # Middleware for HTTPS redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    restart: always

  # watchdog to restart dependent containers
  watchdog:
    build:
      context: ./watchdog
      args:
        TORRENT: ${TORRENT}
    container_name: watchdog
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    depends_on:
      uptime:
        condition: service_healthy
        restart: true
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f watchdog.sh || exit 1" ]
      interval: ${INTERVAL_IN_SECS}
      retries: ${RETRIES}
      start_period: ${START_PERIOD_IN_SECS}
      timeout: ${TIMEOUT_IN_SECS}

volumes:
  portainer_data:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/portainer
      o: bind
  uptime_kuma:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/uptime
      o: bind
  bind_config:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/dns/config
      o: bind
  bind_data:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/dns/data
      o: bind
  bind_records:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/dns/records
      o: bind
  captcha_screenshots:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/byparr/screenshots
      o: bind
  config_vpn:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/torguard-openvpn
      o: bind
  config_sonarr:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/sonarr
      o: bind
  config_radarr:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/radarr
      o: bind
  config_prowlarr:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/prowlarr
      o: bind
  config_qbittorrent:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/qbittorrent/qBittorrent
      o: bind
  config_kometa:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/kometa
      o: bind
  kometa_assets:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/kometa/assets
      o: bind
  config_homarr:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/homarr/configs
      o: bind
  data_homarr:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/homarr/data
      o: bind
  icons_homarr:
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/homarr/icons
      o: bind
  download:
    driver_opts:
      type: none
      device: ${DOWNLOAD_ROOT}
      o: bind
  media:
    driver_opts:
      type: none
      device: ${MEDIA_ROOT}
      o: bind
  media_movies:
    driver_opts:
      type: none
      device: ${MEDIA_ROOT}/Movies
      o: bind
  media_tv:
    driver_opts:
      type: none
      device: ${MEDIA_ROOT}/TV
      o: bind
  media_tmp:
    driver_opts:
      type: none
      device: ${MEDIA_ROOT}/Temporary
      o: bind
  media_other:
    driver_opts:
      type: none
      device: ${MEDIA_ROOT}/Other
      o: bind

networks:
  media:
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: ${DNS_SUBNET}
          gateway: ${DNS_GATEWAY}
```
</details>

<details>
<summary>and here is my directory structure of media project</summary>

![Image](https://github.com/user-attachments/assets/434e7e3c-254d-4733-bce7-ec88d2f3d3e7)
</details>

<details>
<summary> As far as configuration</summary>

You have to include the following label, comma separated for the dependent services
```
labels:
      - "depends_on=service_one, service_two, etc"
```
</details>

let me know if that makes sense, I will go through and make sure everything is up to date and see about updating the instructions

**Comment by Jorman** [comment]
Hi, thank you for your reply!
Now I'll take a good look at how you did it, in the post I opened, I'm mostly referring to the instructions, the build of the docker image
https://github.com/ondrovic/docker-watchdog#step-2-build-the-watchdog-docker-image
doesn't work because the script is in the folder and not in the root, so you need to adapt the Dockerfile
As well as the envs, they are not specified, in the script in fact you will find these variables
```
VPN_CONTAINER="vpn"                 # Name of the VPN container
DEPENDENT_CONTAINERS=("torrent")    # Add dependent containers here
PORT_VAR="${TORRENT}"               # Port defined in .env as TORRENT
```
Maybe the version you use is not the same as the one you uploaded to git?

I notice that you use a very well-structured docker-compose configuration, mine is not like that, also because I have only a few services that depend in cascade on each other, in different docker-composes, since it is not just a matter of vpn
No problem to share my docker-compose reference, there are no secrets.
As you will see, some things are commented on for now, waiting to get your script up and running.
My problem is during nas startup, if the nas is restarted then it is sure qbittorrent will not start, while if I do stop and start the container, via my interface, I manage everything from openmediavault, then there is no problem.
```
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        container_name: pia-wireguard-vpn-proxy
            # labels:
               # - "autoheal=master"
        volumes:
            - ${DOCKER_APPDATA}/pia-wireguard:/pia
            - ${DOCKER_APPDATA}/pia-wireguard:/pia-shared
            - ${UTILITIES}:/${UTILITIES}
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - LOC=italy
            - USER=***
            - PASS=***
            - PORT_FORWARDING=1 #1
            - PORT_PERSIST=1
            - PORT_SCRIPT=${UTILITIES}/scripts/qBittorrent-pia-port.sh 10.0.0.100
            - FIREWALL=1
            - EXIT_ON_FATAL=1
            - VPNDNS=1.1.1.1, 1.0.0.1
            - LOCAL_NETWORK=10.0.0.0/24, 10.8.0.0/29
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        ports:
            # qBittorrent
            - 8081:8081

            # Prowlarr
            - 9696:9696

            # Flaresolverr
            #- 8191:8191

        networks:
            - default
            - authelia-swag_net
        healthcheck:
            test: "ping -c 1 www.google.com || exit 1"
            interval: 60s
            timeout: 5s
            retries: 3
        restart: unless-stopped

    # qBittorrent service
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
#        labels:
#            - "autoheal=slave"
        environment:
            - DOCKER_MODS=linuxserver/mods:universal-cron
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=8081
        volumes:
            - ${DOCKER_APPDATA}/qbittorrent:/config
            - ${DATA}:/data
            - ${SHARING}:/Sharing
            - ${UTILITIES}/scripts:/scripts
            - ${DOCKER_APPDATA}/pia-wireguard:/pia-shared
            - ${DOCKER_APPDATA}/qbittorrent/theme:/theme
        network_mode: "service:vpn"
        depends_on:
            vpn:
                condition: service_started
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped

    gitsync:
        image: registry.k8s.io/git-sync/git-sync:v4.2.3
        container_name: Dracula-for-QBittorrent
        user: "${PUID}:${PGID}"
        restart: unless-stopped
        environment:
            - GITSYNC_REPO=https://github.com/dracula/qbittorrent.git
            - GITSYNC_ROOT=/theme
            - GITSYNC_VERBOSE=4
            - GITSYNC_PERIOD=86400s
        depends_on:
            qbittorrent:
                condition: service_started
                restart: true
        volumes:
            - ${DOCKER_APPDATA}/qbittorrent/theme:/theme

    # Prowlarr service
    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:nightly
        container_name: prowlarr
#        labels:
#            - "autoheal=slave"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_APPDATA}/prowlarr:/config
        network_mode: "service:vpn"
        depends_on:
            vpn:
                condition: service_started
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9696/health"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped

networks:
  default:
  authelia-swag_net:
    external: true
```
I may have to adjust my healthcheck and there is no problem for that.
In this docker-compose that you shared, in fact I see this
```
  # watchdog to restart dependent containers
  watchdog:
    build:
      context: ./watchdog
      args:
        TORRENT: ${TORRENT}
    container_name: watchdog
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
```
And as you see here is present `TORRENT: ${TORRENT}` But which door is it? Because each service provider maybe has different methods, I for example with PIA I have the possibility to have a port forwarding which I use for qBittorrent, but nothing more, to test the connection just ping google in my case

**Comment by ondrovic** [comment]
> https://github.com/ondrovic/docker-watchdog#step-2-build-the-watchdog-docker-image
doesn't work because the script is in the folder and not in the root, so you need to adapt the Dockerfile

yes, in your media stack , you need to have both the  `Dockerfile` and `watchdog.sh` in a folder called `watchdog` or you would have to update your docker compose to point where it's at based on your file.

The reason it's different is because I wrote it and tested it directly in my stack for a couple of months, then decided to release it as kinda a stand alone,  item that others could integrate into their stack, with that being said I didn't test building it as it using Dockerfile or docker compose as most of the items are bogus and just for informational purpose.

> My problem is during nas startup, if the nas is restarted then it is sure qbittorrent will not start, while if I do stop and start the container, via my interface, I manage everything from openmediavault, then there is no problem.

I am not sure I follow, but it sounds like you are using everything for openmediavault, which I haven't used in years.


> And as you see here is present TORRENT: ${TORRENT} But which door is it? Because each service provider maybe has different methods, I for example with PIA I have the possibility to have a port forwarding which I use for qBittorrent, but nothing more, to test the connection just ping google in my case

so this is just my the `${TORRENT}` or whatever the name of the the variable you are using, or port number for example it could be 

```
TORRENT: 6881
-or
TORRENT: ${TORRENT}  // where it's defined in an .env file
```

really all it is doing is this

```
# Create the .env file with the TORRENT value inside the local container
RUN echo "TORRENT=${TORRENT}" > /usr/local/bin/.env
```

Also don't forget you need to ensure that each service you want to monitor has this 

```
labels:
      - "depends_on=<dependent service one>, <dependent service two>, etc "
```

so this might help

```yaml
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        container_name: pia-wireguard-vpn-proxy
            # labels:
               # - "autoheal=master"
        volumes:
            - ${DOCKER_APPDATA}/pia-wireguard:/pia
            - ${DOCKER_APPDATA}/pia-wireguard:/pia-shared
            - ${UTILITIES}:/${UTILITIES}
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - LOC=italy
            - USER=***
            - PASS=***
            - PORT_FORWARDING=1 #1
            - PORT_PERSIST=1
            - PORT_SCRIPT=${UTILITIES}/scripts/qBittorrent-pia-port.sh 10.0.0.100
            - FIREWALL=1
            - EXIT_ON_FATAL=1
            - VPNDNS=1.1.1.1, 1.0.0.1
            - LOCAL_NETWORK=10.0.0.0/24, 10.8.0.0/29
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        ports:
            # qBittorrent
            - 8081:8081

            # Prowlarr
            - 9696:9696

            # Flaresolverr
            #- 8191:8191

        networks:
            - default
            - authelia-swag_net
        healthcheck:
            test: "ping -c 1 www.google.com || exit 1"
            interval: 60s
            timeout: 5s
            retries: 3
        restart: unless-stopped

    # qBittorrent service
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
#        labels:
#            - "autoheal=slave"
        labels:
            - "depends_on:vpn"
        environment:
            - DOCKER_MODS=linuxserver/mods:universal-cron
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=8081
        volumes:
            - ${DOCKER_APPDATA}/qbittorrent:/config
            - ${DATA}:/data
            - ${SHARING}:/Sharing
            - ${UTILITIES}/scripts:/scripts
            - ${DOCKER_APPDATA}/pia-wireguard:/pia-shared
            - ${DOCKER_APPDATA}/qbittorrent/theme:/theme
        network_mode: "service:vpn"
        depends_on:
            vpn:
                condition: service_started
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped

    gitsync:
        image: registry.k8s.io/git-sync/git-sync:v4.2.3
        container_name: Dracula-for-QBittorrent
        user: "${PUID}:${PGID}"
        restart: unless-stopped
        environment:
            - GITSYNC_REPO=https://github.com/dracula/qbittorrent.git
            - GITSYNC_ROOT=/theme
            - GITSYNC_VERBOSE=4
            - GITSYNC_PERIOD=86400s
        depends_on:
            qbittorrent:
                condition: service_started
                restart: true
        labels:
            - "depends_on:qbittorrent"
        volumes:
            - ${DOCKER_APPDATA}/qbittorrent/theme:/theme

    # Prowlarr service
    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:nightly
        container_name: prowlarr
#        labels:
#            - "autoheal=slave"
        # this is bad practice according to the docs for prowlarr, they say you shouldn't use it behind a vpn but if it works for you, go for it
        labels:
            - "depends_on:vpn"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_APPDATA}/prowlarr:/config
        network_mode: "service:vpn"
        depends_on:
            vpn:
                condition: service_started
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9696/health"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
    # watchdog to restart dependent containers
    watchdog:
        build:
        # just make sure you create a folder called watchdog and put the Dockerfile and watchdog.sh in it, should be in the same location as this docker-compose.yml file
        context: ./watchdog
        args:
            TORRENT: 8081
        container_name: watchdog
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pgrep -f watchdog.sh || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5

networks:
  default:
  authelia-swag_net:
    external: true
```
